-- =============================================================================
-- Reset Default Privileges — run as db_manager_role.
-- Revokes any ALTER DEFAULT PRIVILEGES previously set by this role.
-- Safe to run even if defaults were never set (no-op).
-- =============================================================================

ALTER DEFAULT PRIVILEGES IN SCHEMA core
  REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM app_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA config
  REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM app_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA usage
  REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM app_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA ingested
  REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM app_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA analytics
  REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM app_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA core
  REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM admin_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA config
  REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM admin_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA usage
  REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM admin_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA ingested
  REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM admin_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA analytics
  REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM admin_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA internal
  REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM admin_role;
